name: "[Windows] Build TF Examples"

on:
  push:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout The-Forge
      uses: actions/checkout@v3
      with:
        path: The-Forge

    - name: Checkout Custom-Middleware
      uses: actions/checkout@v3
      with:
        path: Custom-Middleware
        repository: ConfettiFX/Custom-Middleware
        ref: ${GITHUB_REF_NAME}  # Checkout the Custom-Middleware branch with the same name as the The-Forge branch we're building

    - name: "[DEBUG] Tree"
      run: tree /A > workspace.tree
    - name: "[DEBUG] Upload Tree"
      uses: actions/upload-artifact@v3
      with:
        name: workspace.tree
        path: workspace.tree

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Vulkan SDK
      run: choco install vulkan-sdk --version 1.2.162.0 -y

    - name: Install VS2017
      run: choco install VisualStudio2017Community visualstudio2017-workload-nativedesktop

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[15.0,16.0)'

    - name: Build
      working-directory: The-Forge
      shell: cmd
      run: python -u ./CI/PyBuild.py --preserveworkingdir
      env:
        VULKAN_SDK: "C:\\VulkanSDK\\1.2.162.0"
