name: "[Android] Build TF Examples"

on:
  push:

env:
  ANDROID_HOME: "C:\\Android\\android-sdk"
  ANDROID_SDK_ROOT: "C:\\Android\\android-sdk"

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout The-Forge
      uses: actions/checkout@v3
      with:
        path: The-Forge

    - name: Checkout Custom-Middleware
      uses: actions/checkout@v3
      with:
        path: Custom-Middleware
        repository: ConfettiFX/Custom-Middleware
        # ref: ${{ github.ref_name }}  # Checkout the Custom-Middleware branch with the same name as the The-Forge branch we're building

    - name: Install Android SDK
      shell: pwsh
      run: |
        Write-Host "Removing any old Android SDKs..."
        Remove-Item -Path "$env:ANDROID_SDK_ROOT" -Recurse -ErrorAction Ignore
        Write-Host "Downloading commandline-tools..."
        Invoke-WebRequest https://dl.google.com/android/repository/commandlinetools-win-8512546_latest.zip -OutFile commandline_tools.zip
        Write-Host "Extracting commandline-tools..."
        Expand-Archive commandline_tools.zip -DestinationPath commandline_tools_extracted
        New-Item "$env:ANDROID_SDK_ROOT/cmdline-tools" -ItemType Directory
        Move-Item -Path commandline_tools_extracted/cmdline-tools -Destination "$env:ANDROID_SDK_ROOT/cmdline-tools"
        Rename-Item "$env:ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" -NewName latest

        Write-Host "Installing Android NDK..."
        Set-Location "$env:ANDROID_SDK_ROOT/cmdline-tools/latest/bin/"
        Write-Output Y | .\sdkmanager.bat "ndk;21.4.7075529"
    
    # - name: "[DEBUG] Add verbosity to Android.mk for shaderc"
    #   shell: pwsh
    #   run: Copy-Item "The-Forge/.github/workflows/modified_Android.mk" "$env:ANDROID_SDK_ROOT/ndk/21.4.7075529/sources/third_party/shaderc/Android.mk"
    
    - name: "[DEBUG] Early build of shaderc"
      shell: cmd
      working-directory: C:\\
      run: ${{ github.workspace }}\\The-Forge\\Scripts\\vulkan\\android_shaderc.bat C:\\Android\\android-sdk\\ndk\\21.4.7075529\\

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Vulkan SDK
      run: choco install vulkan-sdk --version 1.2.162.0

    - name: Install VS2017
      run: choco install VisualStudio2017Community visualstudio2017-workload-nativedesktop visualstudio2017-workload-nativemobile

    - name: Install Android Game Development Extension
      shell: pwsh
      env:
        TEMP: ${{ runner.temp }}
      run: |
        Write-Host "Downloading AGDE..."
        Invoke-WebRequest https://dl.google.com/android/agde/release/62/20220615-181705/AndroidGameDevelopmentExtensionSetup-v22.2.65.exe -OutFile agde_setup.exe
        Write-Host "Starting AGDE installer..."
        ./agde_setup.exe -quiet
        Write-Host "Waiting for AGDE installer to close..."
        Wait-Process agde_setup

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[15.0,16.0)'

    - name: Build
      working-directory: The-Forge
      shell: cmd
      run: python -u ./CI/PyBuild.py --preserveworkingdir --prebuild --android --printbuildoutput
      env:
        VULKAN_SDK: "C:\\VulkanSDK\\1.2.162.0"
